version: '3.7'
services:
  database:
    image: mongo
    container_name: parking_manager
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123
      MONGO_INITDB_DATABASE: parking_db

    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: parkingManager
    ports:
      - 5001:5001
    volumes:
      - .:/user/app

volumes:
  mongo_data:
